[안정은] 바닐라 JS로 Todolist 구현
yujo11/js-todo-mvc pull request #10
Opened 2023-11-29 23:53 UTC by jxxxxe

<a href="https://js-todo-mvc-jeongeun.vercel.app/">데모 사이트</a>

## 🎯 요구사항

- [X] todo list에 todoItem을 키보드로 입력하여 추가하기
- [x] todo list의 체크박스를 클릭하여 complete 상태로 변경 (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [x] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [x] todo list를 더블클릭했을 때 input 모드로 변경 (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [x] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- [x] todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기

## ？ 궁금한 점
1. 지금은 여러번 호출하는 기능은 utils 함수로, 그렇지 않은 것은 components로 분리했는데 이런 분리 로직이 올바른지 궁급합니다
2. 전체/완료한일/미완료일 메뉴를 클릭할 때마다, 투두 아이템들의 클래스에 hidden을 추가/삭제하면서 리스트를 업데이트 하는 방식이 올바른지 궁금합니다
3. 그 외에 궁금한 점들을 pr 메시지로 남겨두었습니다 확인 해주시면 감사하겠습니당

2023-11-30 00:09 UTC, ganjjee commented on src/utils/countTodo.js
> +        $count.textContent = totalCount
이렇게 textcontent에 값을 할당해서, html 요소의 값을 직접 할당하는 방법이 괜찮은지 궁금합니다
이전에 썼던 '렌더링 될 때마다 html 요소를 다시 그리는 방법'은 성능면에서 좋지 않을 것 같아서 이 방법을 사용해보았습니다!

2023-11-30 00:09 UTC, jxxxxe commented on src/main.js
> +new App()
이전엔 main.js가 '타겟 셀렉터를 생성+App 컴포넌트를 생성'하는 기능을 했는데, 이번 과제에서는 템플릿을 사용했기 때문에 App 컴포넌트를 생성하는 기능만 넣었습니다. 
근데 뭔가 App.js를 html의 스크립트로 바로 넣는 방법도 있을 것 같은데.. main.js를 생략하는 것에 대해 어떻게 생각하시는지 궁금합니다.

2023-11-30 00:09 UTC, jxxxxe commented on src/components/TodoItem.js
> +    $item.id = `todoItem-${Date.now()}`
App컴포넌트에서 아이템을 삭제할 때 용이하게 하기 위해 이렇게 Date 객체를 이용해 아이디를 넣어보았습니다. 괜찮은 방법일까요?

2023-11-30 00:09 UTC, jxxxxe commented on src/components/TodoItem.js
> +        this.setState({
가급적이면 상태관리는 App 컴포넌트에서 하는게 좋다고 알고 있는데, 지금처럼 아이템 개별로 상태를 가질 때는 해당 하위 컴포넌트에서 관리해도 괜찮은지 궁금합니다.

2023-12-03 11:48 UTC, yujo11 requested changes
안녕하세요 정은님~ 리뷰가 조금 늦어졌네요 

>지금은 여러번 호출하는 기능은 utils 함수로, 그렇지 않은 것은 components로 분리했는데 이런 분리 로직이 올바른지 궁급합니다

하나의 좋은 기준일 수 있다고 생각합니다.

하지만 util은 일반적으로 도메인 로직에 종속되지 않는 로직을 두고는 하는데요. 도메인(TodoList)을 기준으로 나눠서

생각해보셔도 좋을거 같습니다 ㅎㅎ

>전체/완료한일/미완료일 메뉴를 클릭할 때마다, 투두 아이템들의 클래스에 hidden을 추가/삭제하면서 리스트를 업데이트 하는 방식이 올바른지 궁금합니다

구현하는 데는 다양한 방법이 있겠지만 이 방식도 나쁘다고 생각하지는 않습니다

미션 진행하느라 고생 많으셨어요 정은님~! 코멘트 확인해보시고 다시 리뷰요청 주세요~

2023-12-03 11:48 UTC, yujo11 commented on index.html
> +      </form>
`form`을 사용하셨군요 👍

2023-12-03 11:48 UTC, yujo11 commented on src/App.js
> +}
<img width="48" alt="image" src="https://github.com/yujo11/js-todo-mvc/assets/61097373/230d32c9-a782-44f7-8a33-33c4747c47ec">

file changed에서 이 아이콘이 왜 생기는지 찾아보셔도 좋을거 같아요

2023-12-03 11:48 UTC, yujo11 commented on src/App.js
> +}
추가로 `prettier`같은 코드 포맷터를 사용하지 않고 있다면 사용해보시는걸 추천 드립니다!

2023-12-03 11:48 UTC, yujo11 commented on src/components/TodoItem.js
> +    $item.id = `todoItem-${Date.now()}`
네네 좋은 방법이라고 생각합니다 👍 

Date객체를 사용하던 어떤 방법을 사용하던 각각의 Item이 고유한 키(Primary Key)를 갖게 하는 방법은 많이 사용되는 방법입니다

2023-12-03 11:48 UTC, yujo11 commented on src/components/TodoItem.js
> +        this.setState({
"가급적이면 상태관리는 App 컴포넌트에서 하는게 좋다고 알고 있는데" 

왜 상태관리를 App 컴포넌트에서 하면 좋은걸까요~?

2023-12-03 11:48 UTC, yujo11 commented on src/main.js
> +new App()
저는 `script`가 여러 곳에서 나뉘어서 실행되는 것보다는 `main.js` 같은 파일을 두고 JavaScript가 init되는 지점을 관리하는 방법을 선호하는 편입니다.

정은님이 생각하시기에 두 방법은 어떤 차이가 있을까요?

2023-12-03 11:48 UTC, yujo11 commented on src/components/TodoMenu.js
> +            onSelectMenu($filter.classList[0])
`classList[0]`이라는 코드는 classList의 0번째 인덱스에 위치한 어떤 값을 사용한다는 것 외에 다른 의미를 전달하기 어렵고, 인덱스는 쉽게 변할 수 있는 요소이기 때문에 향후 유지보수에서도 [0]번째에 위치한 요소가 쉽게 변경 될 여지가 있는데요.

다른 방법을 사용해 볼 수 있을까요?

2023-12-03 11:48 UTC, yujo11 commented on src/utils/countTodo.js
> +        $count.textContent = totalCount
간단하게 텍스트를 업데이트 하는 경우 괜찮다고 생각합니다! 👍

2023-12-03 11:48 UTC, yujo11 commented on src/components/TodoItem.js
> +            isCompleted: isCompleted ? false : true
아래처럼만 사용해도 될거 같네용~

```suggestion
            isCompleted: !isCompleted
```

2023-12-03 11:48 UTC, yujo11 commented on src/App.js
> +    }
전체 TodoList를 App의 state로 관리하면 count를 알아내는 방법도 많이 간소화 시킬 수 있을거 같네요

2023-12-13 06:54 UTC, jxxxxe reviewed
안녕하세요 멘토님! 리뷰반영이 늦어진 점 죄송합니다 ㅜ^ㅜ
1. prettier를 적용하여 EOL을 삽입 해주었습니다.
2. App 컴포넌트에서 count를 상태 관리하던 것에서 list를 관리하는 것으로 변경하였습니다
3. 하단에 메뉴 변경 시 클래스 이름을 추출하기 위해 `classList[0]`처럼 인덱스로 표현하던 것에서 `className`으로 변경하였습니다.

이외에 멘토님이 제 의견을 물어보신 것에 대해서는.. 조금 더 생각해서 오늘 내로 답글을 남기도록 하겠습니다!!

2023-12-13 06:54 UTC, ganjjee commented on src/components/TodoMenu.js
> +            onSelectMenu($filter.classList[0])
```suggestion
            onSelectMenu($filter.className);
            $filter.classList.add("selected");
```
`selected` 클래스명을 붙이기 전에는 클래스 이름이 `all`, `active`, `completed` 중 하나니까 `onSelectMenu`를 먼저 하는 방식으로 바꿔보았습니다!
더 명시적으로 수정하는게 좋을지 조언해주시면 감사하겠습니닷

2023-12-13 07:15 UTC, jxxxxe commented on src/App.js
> +    }
리스트로 변경해보았습니다! 덕분에 코드가 여러 부분에서 간소화 된 것 같아요!
근데 궁금한 점이 있습니다
지금처럼 메뉴를 누를 때마다 filter로 토글 여부를 체크하는 방법은 많은 연산이 필요할 것 같다는 생각이 들었습니다.
그래서 completed 리스트를 따로 관리하는 방법도 생각해 보았는데, 이 방법은 토글 시 아이템이 completed 리스트에 맨 밑에 추가가 되어 처음 아이템을 등록한 순서와 일치하지 않는 문제가 있었습니다.

그래서 리스트로 등록하는 방법 중 다른 좋은 방법이 있을지가 궁급합니다!

2023-12-16 05:31 UTC, closed without merging