[이재영] 바닐라 JS로 Todolist 구현
yujo11/js-todo-mvc pull request #7
Opened 2023-11-27 03:53 UTC by Jae0o

[데모 사이트 링크](https://vanilla-js-todo-mvc.vercel.app/)

- [x] todo list에 todoItem을 키보드로 입력하여 추가하기
- [x] todo list의 체크박스를 클릭하여 complete 상태로 변경 (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [x] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [x] todo list를 더블클릭했을 때 input 모드로 변경 (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [x] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- [x] todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기

1. 이번 과제에서 이벤트를 올바르게 사용했는지 궁금합니다! 특히 double click 이벤트를 생성하고 제거하는 부분이 올바른 방법이었을지 궁금합니다!

2023-11-30 15:44 UTC, yujo11 requested changes
안녕하세요 재영님~

CSS까지 모두 새로 구현하셨군요 JavaScript 구현만 해도 시간이 걸리셨을텐데 멋집니다 👍 👍 (다음부터는 요구사항만 구현하셔도 됩니다 ㅋㅋ)

>이번 과제에서 이벤트를 올바르게 사용했는지 궁금합니다! 특히 double click 이벤트를 생성하고 제거하는 부분이 올바른 방법이었을지 궁금합니다!

전체적으로 알맞게 사용하신거 같아요 ㅎㅎ

소소하게는 `keydown`과 `keyup` 이벤트는 어떤 차이가 있는지 찾아보시면 좋을거 같습니다~

>double click 이벤트를 생성하고 제거하는 부분이 올바른 방법이었을지 궁금합니다!

이 부분은 어디에서 이벤트를 제거했는지 자세하게 적어주시면 확인해보겠습니다

>이번 과제에서 적용하지 못하고 고민만 했던 부분이 todo를 더블클릭하여 수정 모드로 전환된후, 해당 contenteditable 부분 요소 외 다른 요소를 클릭했을때 수정 모드가 완료되는 클릭 event를 추가로 적용하고 싶었습니다!
그런데 과제 수행중 이벤트를 너무 많이 사용하는것 같아 적용하지 않고 제출 하게 되었습니다.. 🥹
원래 계획으로는 TodoList component에서 더블클릭을 이벤트를 통해 target.addEventListener("keydown", onEditingHandler); 해당 부분 밑에 추가적으로 click 이벤트를 걸어 수정 모드를 취소하는 방법을 생각했는데 괜찮은 방법이었을지
혹은 더 좋은 방법이있었을지 궁금합니다!

EventListener가 중첩으로 등록되면서 어떤 동작으로 인해 여러 개의 동작이 함께 트리거 되거나 불필요한 이벤트가 많이 등록 된 경우는 문제가 되곘지만 구현 의도에 맞게 이벤트리스너를 여러 개 등록하는건 문제가 되지 않을거 같아요

생각하신대로 구현해보셔도 좋을거 같습니다

>경고 알림에 대한 메세지를 하나의 constants 파일에 분리하여 관리하였는데 분리하는 과정에 궁금증이 생겼습니다!
분리하는 방법이 더 관리하기 좋은 방법일지 경고가 발생하는 위치에서 직접 관리하는 방법이 더 편한 방법일지에대해 궁금합니다

이 부분은 다른 변수들을 선언할 때도 공통적으로 적용되는 부분인데 해당 상수가 사용되는 범위를 생각해보시면 될거 같아요

특정 파일 내에서만 사용되는 상수라면 하나의 파일에 있는게 응집도가 높아 보다 관리하기 편할거 같네요


고생 많으셨습니다 재영님 ~ 👍 👍 👍

2023-11-30 15:44 UTC, yujo11 commented on src/css/footer.css
CSS도 모두 새로 작성하셨군요 고생 많으셨습니다 👍 👍 👍

2023-11-30 15:44 UTC, yujo11 commented on src/function/validate.js
> +  return true;
아래처럼 축약해서 표현하셔도 좋을거 같아요

```suggestion
  return prevData !== currentData
```

2023-11-30 15:44 UTC, yujo11 commented on src/function/validate.js
> +  return true;
여기도 위 내용과 마찬가지입니다~

그런데 이런 함수가 존재해야할 이유를 잘 모르겠는데 이 함수를 만들어서 사용하신 이유가 있을까요?

아래와 같이 A, B 방법이 존재할 때 A 방법이 훨씬 직관적으로 느껴지네용

```
// A
if (someValue === somesomeValue)

// B
if (isUpdatedPrimitiveValue(someValue, somesomeValue)
```

2023-11-30 15:44 UTC, yujo11 commented on src/Constants.js
상수화를 꼼꼼하게 하셨군요 👍

2023-11-30 15:44 UTC, yujo11 commented on src/Constants.js
> +export const ALERT_MESSAGE_GET_LIST = "Todo 들을 가져오다가 실패했습니다. 🥹";
아래와 같이 객체로 한번 묶어서 사용해보셔도 좋을거 같아요

```suggestion
export const ALERT_MESSAGE = {
  SET_LIST: ...,
  UPDATE_LIST: ...
}
```

2023-11-30 15:44 UTC, yujo11 commented on src/Components/Footer/Footer.js
> +export default function Footer({ target, state, onChange }) {
`class`대신 function을 사용하신 이유가 있을까요~?

2023-11-30 15:44 UTC, yujo11 commented on src/Components/Header/TodoForm.js
> +import { ALERT_MESSAGE_EDIT, ALERT_MESSAGE_INPUT, PLACE_HOLDER } from "../../Constants.js";
`PLACE_HOLDER`라는 이름은 너무 범용적이라서 어떤 값이 담겨 있을지 예측이 어려운데요.

의미를 더 잘 드러낼 수 있도록 명명해보셔도 좋을거 같습니다~

2023-11-30 15:44 UTC, yujo11 commented on src/Components/Header/TodoForm.js
> +  formElement.appendChild(inputElement);
이런 요소들은 항상 존재하기 때문에 처음부터 html 파일에 있었어도 될거 같은데 이렇게 App이 로딩 된 이후에 생성해서 넣어주시는 이유가 있나요?

2023-11-30 15:44 UTC, yujo11 commented on src/Components/Header/TodoForm.js
> +    if (newTodo.length < 2) {
`2`라는 매직 넘버도 상수화 해보시면 좋겠네요~

2023-11-30 15:44 UTC, yujo11 commented on src/Components/List/TodoList.js
> +      event.preventDefault();
`keydown`이벤트의 기본 동작 중 어떤 동작을 방지하기 위해 `preventDefault`를 사용하셨나요?

2023-11-30 15:44 UTC, yujo11 commented on src/Components/List/TodoList.js
> +    if (event.key === "Enter" || event.key === "Escape") {
현재는 `Enter` 키가 입력됐을 때와 `Esc`키가 입력되었을 때의 동작이 같은데 요구사항에 따라 분기를 추가해보셔도 좋겠네요~

2023-11-30 15:44 UTC, yujo11 commented on src/Components/List/TodoList.js
> +    });
`setTimeout`으로 로직을 작성하신 이유가 있나요?

2023-12-02 11:19 UTC, Jae0o commented on src/Components/Footer/Footer.js
> +export default function Footer({ target, state, onChange }) {
이전 커리큘럼 과제였던 TodoList 만들기 과제에서 `class` 와 `function` 두개 모두 사용해 각각 TodoList를 구현해본 경험이 있었는데, 당시 저에게는 `function`이 좀 더 친숙하고 편리했던 경험으로 인해 이번 과제에서도 `function`을 사용한것 같습니다. 🤔

2023-12-02 11:19 UTC, Jae0o commented on src/Components/Header/TodoForm.js
> +  formElement.appendChild(inputElement);
이건 사실 제가 vanillaJS를 학습하기 이전에 vanillaJS가 별도의 라이브러리나 프레임워크인줄 알았었는데 🥹 이번 코스를 통해 알게되었고 이후로 위와같은 방식대로 사용 해와서 한번도 생각해보지 못했던 부분이라 한번 생각해보았습니다!
개인적 생각으로는 물론 현재 과제에서는 재사용될 일이 없을것 같지만 별도의 component로써 재사용성을 위해서 내부에서 element를 생성하는 방식이 좋았던것 같고, 
각 component 별로 js 파일을 읽는다고 했을때 어떤 element가 존재하고 해당 element가 어떤 속성을 가지고 있는지 확인하기 좋을것 같습니다.

2023-12-02 11:19 UTC, Jae0o commented on src/Components/List/TodoList.js
> +    });
이전 notion project에서 contenteditable 속성을 다루면서 당시에 focus속성이 event 내부에서 서 실행될때 정상 작동되지 않는 문제를 많이 경험해서 혹시 모를 예외 상황에 대비해 focus 함수 실행을 지연시키기 위해 사용했습니다.

2023-12-02 11:19 UTC, Jae0o commented on src/Components/List/TodoList.js
> +    if (event.key === "Enter" || event.key === "Escape") {
앟 제가 요구사항을 잘못 이해했네요ㅜ 수정해보겠습니다!

2023-12-02 11:19 UTC, Jae0o commented on src/Components/List/TodoList.js
> +      event.preventDefault();
enter로 인한 줄바꿈을 방지하기 위해 사용했습니다!

2023-12-02 11:19 UTC, Jae0o commented on src/Constants.js
> +export const ALERT_MESSAGE_GET_LIST = "Todo 들을 가져오다가 실패했습니다. 🥹";
앟.. 이런 방법이.. 별도로 분리할 생각만 했는데 감사합니다

2023-12-02 11:19 UTC, Jae0o commented on src/function/validate.js
> +  return true;
함수 이름을 통해 직관적으로 표현하는게 좋다고 생각한점도 있었고, 동일한 목적의 조건문에서 어느 부분에서는`isUpdatedReferenceValue`  함수를 사용하고 있다보니 일관성을 유지하기위해.... 사용 했던것 같습니다 🥹 변경해보겠습니다!

2023-12-02 11:19 UTC, Jae0o commented on src/function/validate.js
> +  return true;
앟.. 이부분을 완전 놓치고 있었네요 .. 감사합니다!

2023-12-02 11:47 UTC, Jae0o commented on src/function/validate.js
> +  return true;
8649f8602f5c2aa9be4ac9c4c074cab7b27e6ea5 
수정하였습니다 😀

2023-12-02 11:48 UTC, Jae0o commented on src/function/validate.js
> +  return true;
8649f8602f5c2aa9be4ac9c4c074cab7b27e6ea5 함수를 사용하지 않는 방향으로 수정해보았습니다!

2023-12-02 11:49 UTC, Jae0o commented on src/Components/Header/TodoForm.js
> +    if (newTodo.length < 2) {
775c899a85fd2248950bab80a9e9270d47a0b93d 수정해보았습니다 감사합니당 👍

2023-12-12 22:56 UTC, yujo11 approved these changes
안녕하세요 재영님~~

고생 많으셨습니다 추가로 남긴 코멘트들은 확인해보시고 다음에 구현하실 때 고려해보시면 좋을거 같습니다! 👍

2023-12-12 22:56 UTC, yujo11 commented on src/Components/Footer/Footer.js
커밋 내역을 따라가면서 변경사항을 보고 있는데 이 커밋은 이름이 없네요 ㅎㅎ

<img width="447" alt="image" src="https://github.com/yujo11/js-todo-mvc/assets/61097373/e0a4fe6c-483a-4781-91dd-b2277e3b691f">

2023-12-12 22:56 UTC, yujo11 commented on src/function/validate.js
>  }
이미 만들어 놓은 뭔가를 지우는게 쉽지 않은 일인데 멋집니다 재영님 👍

2023-12-12 22:56 UTC, yujo11 commented on src/Constants.js
> +};
객체 사용 좋네요 👍

2023-12-12 22:56 UTC, yujo11 commented on src/Constants.js
지금 상수의 이름만으로는 담겨있을 내용을 유추하기가 조금 어려운데요. 

이름이 길어지더라도 조금 더 명확한 이름을 가지면 좋을거 같습니다!

2023-12-12 22:56 UTC, yujo11 commented on src/Constants.js
> +  SET_LIST: "새로운 TodoList 업로드에 실패했습니다. 🥹",
아래 같은 식으로요!

`LIST_UPLOAD_FAIL: "새로운 TodoList 업로드에 실패했습니다. 🥹",`

2023-12-12 22:56 UTC, yujo11 commented on src/Components/Footer/Footer.js
> +export default function Footer({ target, state, onChange }) {
아하 그렇군요 다음에 바닐라 자바스크립트로 구현하실 때는 익숙하지 않은 `class` 같은 방식으로 구현해보셔도 좋을거 같습니다!

2023-12-12 22:56 UTC, closed without merging

2023-12-13 09:29 UTC, Jae0o commented on src/Components/Footer/Footer.js
오잉? .. 제가 실수로 입력을 하는걸 깜빡하고 눌렀나보네요 ㅠ

리뷰에 남겨 주셨던 `isUpdatedPrimitiveValue`함수를 제거하고 가독성을 위해서 비교 연산자로 대체한 부분의 커밋입니다!

2023-12-13 09:30 UTC, Jae0o commented on src/Constants.js
> +};
상수를 이제까지 항상 하나의 변수로 관리했는데.. 알려주신 덕분에 모든 상수 관리를 객체로 먼저 생각하게 된것 같습니다 ㅎㅎ 감사합니다 ☺️

2023-12-13 09:31 UTC, Jae0o commented on src/Constants.js
> +  SET_LIST: "새로운 TodoList 업로드에 실패했습니다. 🥹",
다음 과제에서 한번 적용해보겠습니다 😀