[신종욱] 바닐라 JS로 Todolist 구현하는 과제
yujo11/js-todo-mvc pull request #8
Opened 2023-11-28 04:41 UTC by dlsxjzld

* TodoList 사이트 : https://js-todo-liart.vercel.app

## 🎯 요구사항
- [x] todo list에 todoItem을 키보드로 입력하여 추가하기
- [x] todo list의 체크박스를 클릭하여 complete 상태로 변경 (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [x] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [x] todo list를 더블클릭했을 때 input 모드로 변경 (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [x] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- [x] todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기
## 추가 구현사항
- [x] todo list를 더블클릭했을 때 input 모드로 변경되면서 자동으로 focus 하기
- [x]  todo list를 더블클릭했을 때 input 모드로 변경된 상태에서, 추가 입력 후 수정 완료하지 않은 상태에서 필터 바꿔도 추가 입력한 데이터 임시저장 (debouce를 통해 구현)

## ✅ PR 포인트 & 궁금한 점 
* innerHTML을 안쓰고 만드는 것과 코드가 일관성을 갖도록 만드는 것에 집중해봤습니다.
* 많이 부족하기에 궁금하거나 잘못된 부분이 있다면  편하게 말씀해주시면 좋겠습니다!! 

1. 상태가 바뀌는 부분만 렌더링을 하고 싶은데 바닐라 자바스크립트는 전체를 렌더링하는 방법밖에 없을까요?? 그래서 리액트가 나오게 된건지 궁금합니다! 
2. 주석을 아예 쓰지 않았는데 잘 이해가 되는지 궁금합니다. 
3. 전반적으로 요구사항에 맞게 잘 구현 되었는지 궁금합니다. 

2023-12-02 04:17 UTC, yujo11 requested changes
안녕하세요 종욱님~

전체적으로 깔끔하게 구현해주셨는데요. 코멘트 남긴 부분 확인해주시면 좋을거 같습니다~

>상태가 바뀌는 부분만 렌더링을 하고 싶은데 바닐라 자바스크립트는 전체를 렌더링하는 방법밖에 없을까요?? 그래서 리액트가 나오게 된건지 궁금합니다!

아닙니다. React 역시 JavaScript로 구현되어 있는데요. 바닐라 자바스크립트에서 항상 전체를 렌더링 할 수 밖에 없었다면 React도 부분적으로 렌더링하는 방법이 불가능했겠죠 ㅎㅎ

여러가지 방법이 존재하는데 React에서 어떻게 변경 된 부분만 업데이트 하는지 찾아보셔도 좋을거 같고, Web Component에 대해서 찾아보셔도 좋을거 같아요~

>주석을 아예 쓰지 않았는데 잘 이해가 되는지 궁금합니다.

전반적인 코드흐름은 잘 이해가 되었습니다

>전반적으로 요구사항에 맞게 잘 구현 되었는지 궁금합니다. 

잘 구현하신거 같습니다 👍 

미션 진행하느라 고생 많으셨습니다 ㅎㅎ 👍 👍 👍

2023-12-02 04:17 UTC, yujo11 commented on src/utils/storage/localStorage.js
이름도 `getTodoList`, `setTodoList`로 명명되어 있어서 사용처가 한정적인 느낌을 받는데 굳이 `key`를 인자로 받아서 사용할 필요가 있을까요?

2023-12-02 04:17 UTC, yujo11 commented on src/utils/stringToNumber.js
> +    if (isNaN(changedString)) {
`Number.isNaN`과 `isNaN`은 어떻게 다를까요~?

2023-12-02 04:17 UTC, yujo11 commented on src/utils/stringToNumber.js
> +    return string;
에러가 발생했을 때 원래 string을 반환해주시는 이유가 있을까요?

2023-12-02 04:17 UTC, yujo11 commented on src/utils/stringToNumber.js
> +    return string;
`stringToNumber`의 함수를 타입으로 적어보면 아래와 같을텐데요.

```js
stringToNumber(string: string) : string | number
```

하나의 함수에서 여러 타입을 반환하는 경우 사용하는 곳에서도 어떤 타입이 반환되었는지 확인하면서 사용해야 하는데요.

함수를 작성하신 의도와 일치하는지 생각해보시면 좋을거 같아요

2023-12-02 04:17 UTC, yujo11 commented on src/components/todoList/TodoList.js
> +    const fragment = document.createDocumentFragment();
오 `fragment`를 사용하셨군요 👍

2023-12-02 04:17 UTC, yujo11 commented on src/components/todoList/TodoList.js
> +    if (inputElements != null && selectedTodo != null) {
`!==` 대신 `!=`를 사용하신 이유가 있을까요?

2023-12-02 04:17 UTC, yujo11 commented on src/components/todoList/TodoItemContent.js
> +    if (isEditing === true) return;
전체적으로 `===`을 통해 엄밀하게 비교 하고 있는 부분들이 있는데 Truthy, Falsy한 값으로도 걸러질 수 있는 조건문이라면 아래처럼 축약해서 사용해보셔도 좋을거 같아요
```suggestion
    if (isEditing) return;
```

2023-12-02 04:17 UTC, yujo11 commented on src/components/todoList/TodoItem.js
> +      }, 500);
이 로직은 어떤거 때문에 필요한걸까요?

2023-12-02 04:17 UTC, yujo11 commented on src/App.js
> +      return whatTodo;
아래처럼 구현해도 괜찮을꺼 같네용

```suggestion
      return todos.filter((todo) => !todo.isCompleted);
```

2023-12-05 06:28 UTC, dlsxjzld commented on src/App.js
> +      return whatTodo;
새로운 변수를 만들어도 쓰는 곳이 없으니까 바로 return 하는 것이 더 괜찮은 것 같네요!! 좋은 의견 감사합니다! 😊

2023-12-05 06:28 UTC, dlsxjzld commented on src/components/todoList/TodoItem.js
> +      }, 500);
input에 입력한 값들을 임시저장하기 위해 setTempTodo를 통해 localStorage에 key와 value를 저장하려고 했습니다. 
debounce를 쓰지 않고 키보드를 계속 치면 setTempTodo가 계속 실행됩니다. 함수의 연속적인 실행을 막고 마지막으로 입력된 값만 저장하고 싶어서 debounce를 쓰게 되었습니다!! 😊

2023-12-05 06:28 UTC, dlsxjzld commented on src/components/todoList/TodoItemContent.js
> +    if (isEditing === true) return;
boolean 값으로만 확인하고자 엄밀하게 비교했는데 멘토님 의견대로 축약해서 사용해도 좋을 것 같네요!! 
좋은 의견 감사합니다 😊

2023-12-05 06:28 UTC, dlsxjzld commented on src/components/todoList/TodoList.js
> +    const fragment = document.createDocumentFragment();
반복문을 통해 엘리먼트를 만들때 appendChild를 쓰면 Dom 트리가 매번 새로 갱신되면서 퍼포먼스에 악영향을 줄 수 있다고 해서 써봤습니다! 😊

2023-12-05 06:28 UTC, dlsxjzld commented on src/components/todoList/TodoList.js
> +    if (inputElements != null && selectedTodo != null) {
null 값과 undefined를 동시에 잡아내기 위해 !=를 써봤습니다! 😊

2023-12-05 06:28 UTC, dlsxjzld commented on src/utils/storage/localStorage.js
저도 만들면서 key를 굳이 넘길 필요가 있을까? 고민해봤었는데 필요 없는 것 같네요!! 좋은 의견 감사합니다!! 👍
추상화에 대해 고민을 하는데 매번 어렵네요 🤔

2023-12-05 06:28 UTC, dlsxjzld commented on src/utils/stringToNumber.js
> +    if (isNaN(changedString)) {
이건 생각해보지 못했는데 좋은 화두를 던져주셔서 감사합니다!! 
isNaN은 값이 숫자인지 확인하기 전에 타입을 숫자 타입으로 변경해서 확인하네요!
isNaN이 Number.isNaN보다 더 엄격하게 확인하는 것으로 이해했는데 제가 올바르게 이해한 것이 맞을까요??🤔

2023-12-05 06:28 UTC, dlsxjzld commented on src/utils/stringToNumber.js
> +    if (isNaN(changedString)) {
그리고 isNaN을 사용한다면 이렇게 바꾸는 것이 더 괜찮을까요??
```suggestion

    if (isNaN(string)) {
        const changedString = Number(string);
```

2023-12-05 06:28 UTC, dlsxjzld commented on src/utils/stringToNumber.js
> +    return string;
default 값을 전달하려고 원래 string을 전달하려고 했는데 이렇게 하면 string을 Number로 변환해서 전달한다는 원래 의도와 다른 것 같네요!! 🤔
좋은 의견 감사합니다! 😊

2023-12-10 05:12 UTC, yujo11 commented on src/utils/stringToNumber.js
> +    if (isNaN(changedString)) {
네네 올바르게 이해하셨습니다 종욱님 👍 

이전에 모각코 할 때 말씀 드렸던 것처럼 `==` `===` 같은 차이라고 생각해주시면 됩니다. 

실제 프로덕션 레벨에서 코드를 작성할 때는 예상치 못한 사이드 이펙트를 피하기 위해 `==` 대신 `===`을 많이 사용하는 것처럼  `isNaN` 대신 `Number.isNaN`을 더 많이 사용하는 편인데요. 이 점도 참고하시면 좋을거 같습니다~

2023-12-10 05:20 UTC, yujo11 approved these changes
안녕하세요 종욱님~

추가로 코멘트 몇가지 남겼는데 추가로 남긴 코멘트들은 확인해보시고 이후에 코드 작성하실 때 적용해보시거나 고민해보시면 좋을거 같습니다!

한가지 더 첨언하면 구현 과정에서는 꼼꼼하게 커밋 남겨주셨는데 리뷰 반영할 때 남기신 "코드 리뷰 반영" 커밋은 커밋명으로 어떤 작업을 진행했는지 유추하기가 어려워서 조금 아쉬웠습니다 😅

<img width="396" alt="image" src="https://github.com/yujo11/js-todo-mvc/assets/61097373/7aa4809e-7798-479a-91e3-c5e3f4890c77">

미션 진행하느라 고생 많으셨습니다 종욱님 ~~ 👍 👍 👍

2023-12-10 05:20 UTC, yujo11 commented on src/App.js
>      }
이런 조건문은 아래처럼 명확하게 조건을 지정해서 사용하거나 `switch - case` 문의 사용도 고려해볼 수 있을거 같네요~
```js
  function filterTodos({ todos, todoFilter }) {
    if (todoFilter === 'allTodo') {
      return todos
    } 

    if (todoFilter === 'whatTodo') {
      return todos.filter((todo) => todo.isCompleted === false)
    } 

    if (todoFilter === someThing){
      return todos.filter((todo) => todo.isCompleted === true)
    }
```

2023-12-10 05:20 UTC, yujo11 commented on src/App.js
>      }
아래처럼 축약문을 사용해 표현하는 것도 같이 고려해보시면 좋겠네요~

```js
    if (todoFilter === 'whatTodo') {
      return todos.filter((todo) => !todo.isCompleted)
    } 

    if (todoFilter === someThing){
      return todos.filter((todo) => todo.isCompleted)
    }
```

2023-12-10 05:20 UTC, yujo11 commented on src/utils/storage/localStorage.js
> +export const getTodoList = (defaultValue) => {
여기에서 default parameter를 이용해줘도 좋을거 같네요~

```js
export const getTodoList = (defaultValue = []) => {
```

2023-12-11 17:56 UTC, closed without merging