[최훈오] 바닐라 JS로 Todolist 구현
yujo11/js-todo-mvc pull request #9
Opened 2023-11-28 06:01 UTC by Whoknow77

[배포링크](https://js-todo-mvc.vercel.app/)

🎯 요구사항
- [x] todo list에 todoItem을 키보드로 입력하여 추가하기
- [x] todo list의 체크박스를 클릭하여 complete 상태로 변경 (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [x] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [x] todo list를 더블클릭했을 때 input 모드로 변경 (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [x] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기 
- [x] todolist의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기

✅ PR 포인트 & 궁금한 점
- 데브코스 들어온 이후로 강의를 통해 바닐라 자바스크립트는 SPA형식으로만 구현해왔는데 우선 기존 방식으로 구현해보고 디벨롭하는 과정을 경험하고 싶어서 다른 방식으로 구현해 봤습니다.
- 한 번에 한 `todo`만 수정이 가능하도록 기능을 구현하던 중 `classList.add`, `classList.remove`을 통해 
관리되던 `editing`을 데이터로 관리하도록 방식을 변경했더니 렌더링에 있어서 일관성은 지켜지겠지만 DOM 접근이 잦아져 성능이 나빠짐을 느끼도 하고 `autofocus`를 구현하는데 까다로워 다시 기존의 방식으로 돌아왔는데 이 구조에서 어떤 방식이 더 좋을까요?
- 필터 옵션이 button 태그가 아닌 링크가 바뀌는 a 태그여서 주소의 hash값에 따라 필터링을 하였습니다. a 태그를 사용하신 이유가 따로 있으신가요?

2023-12-03 14:31 UTC, yujo11 requested changes
안녕하세요 훈오님

전체적으로 코드를 깔끔하게 잘 작성해주셨네요 리뷰 남길 부분도 많지 않았습니다 👍 👍 👍 

>데브코스 들어온 이후로 강의를 통해 바닐라 자바스크립트는 SPA형식으로만 구현해왔는데 우선 기존 방식으로 구현해보고 디벨롭하는 과정을 경험하고 싶어서 다른 방식으로 구현해 봤습니다.
==> SPA 형식으로 리팩토링 하였습니다. 혹시 가능하시다면 두 방식 모두 리뷰해주시면 정말 감사하겠습니다!!

request-change로 변경해뒀는데 코드 이전 버전으로 롤백해서 다시 리뷰 요청주시면 보고 리뷰 드리겠습니다

>필터 옵션이 button 태그가 아닌 링크가 바뀌는 a 태그여서 주소의 hash값에 따라 필터링을 하였습니다. a 태그를 사용하신 이유가 따로 있으신가요?

어딘가에서 가져와서 요구사항을 간소화 시켜 만든거라 큰 이유는 없었습니다 ㅎㅎ

>todo를 필터링, 렌더링 하는 부분이 들어간 부분들을 따로 utils로 빼도 되나요?

이 부분은 도메인 로직을 분리해서 생각해보셔도 좋을거 같아요.

보통 util로 사용하는 함수들은 도메인 로직과 무관하게 어디서든 사용할 수 있는 함수들인데요.

필터링, 렌더링 하는 부분은 현재 상태로 봤을 때는 util 함수라기보다는 도메인 로직에 따라 동작하는 함수로 보여요.

이 부분을 추상화해서 util성 있게 만들 수 있다면 util로 분리하는 것도 좋겠지만 현재의 형태로는 util이라는 이름이 조금 어색하게 느껴지긴 합니다 ㅎㅎ

>현재 count는 따로 상태로 관리하고 있지 않은데 상태로 관리하는 것이 더 나은가요?

이미 존재하는 상태(todoList)를 통해 가져올 수 있는 상태이기 때문에 꼭 상태로 존재하지 않아도 괜찮을거 같습니다.

---

미션 진행하느라 고생 많으셨습니다 훈오님 👍 👍 👍

2023-12-03 14:31 UTC, yujo11 commented on src/App.js
> +	this.state = getItem("todolist", [])
key 값은 실수하기가 쉬운 부분이라 상수로 만들어서 사용해보셔도 좋을거 같아요

2023-12-03 14:31 UTC, yujo11 commented on src/components/TodoForm.js
> +	$target.addEventListener("keydown", (e) => {
`keydown`과 `keyup`은 어떤 차이가 있을까요?

2023-12-03 14:31 UTC, yujo11 commented on src/components/TodoList.js
> +		})
`early return`을 활용해보셔도 좋을거 같아요~

2023-12-03 14:31 UTC, yujo11 commented on utils/filterTodo.js
> +	}
`switch - case`문을 이용해 깔끔하게 표현해주셨군요 👍 👍

2023-12-03 16:45 UTC, Whoknow77 commented on src/components/TodoList.js
> +		})
> `early return`을 활용해보셔도 좋을거 같아요~

지난 과제들에서는 사용했었는데 이번에는 생각이 안났네요ㅠㅠ 감사합니다!!

2023-12-03 16:52 UTC, Whoknow77 commented on src/components/TodoForm.js
> +	$target.addEventListener("keydown", (e) => {
> `keydown`과 `keyup`은 어떤 차이가 있을까요?

순서대로 '키보드에서 눌렀을 때', '키보드에서 손을 뗐을 때' 실행된다는 차이가 있습니다.

여기까지는 강의 들으면서 알게 된 사실이었는데 용도를 몰라 찾아보니 각각 '연속적인 입력이 필요할 때', '단축키, 텍스트 입력 처리'등에 사용된다는 것을 알게 되었습니다.

2023-12-03 17:44 UTC, Whoknow77 commented
> request-change로 변경해뒀는데 코드 이전 버전으로 롤백해서 다시 리뷰 요청주시면 보고 리뷰 드리겠습니다.

다시 코드를 보니 상태가 없을 뿐 전체적으로 돌아가는 로직은 거의 유사해서 지금 리뷰 만으로 충분한 것 같아서 따로 리뷰를 안해주셔도 될 것 같습니다!! 감사합니다 ㅎㅎ

2023-12-11 17:55 UTC, closed without merging

2023-12-11 17:56 UTC, yujo11 commented on src/App.js
> +import { STORAGE_KEY } from "./constants/storageKey.js"
`STORAGE_KEY`라는 너무 범용적인 이름보다는 특정할 수 있는 이름을 지어보셔도 좋을거 같네요 ㅎㅎ

2023-12-11 17:56 UTC, yujo11 commented on src/components/TodoForm.js
> +	$target.addEventListener("keyup", (e) => {
아주 좋습니다! 👍 👍

2023-12-11 17:56 UTC, yujo11 commented on src/components/TodoList.js
early return을 적절하게 활용하셨군요 👍

2023-12-13 09:48 UTC, Whoknow77 commented on src/App.js
> +import { STORAGE_KEY } from "./constants/storageKey.js"
> `STORAGE_KEY`라는 너무 범용적인 이름보다는 특정할 수 있는 이름을 지어보셔도 좋을거 같네요 ㅎㅎ

TODO_STORAGE_KEY로 바꿔보도록 하겠습니다!